
language: erlang

matrix:

  include:
    - os: linux
      dist: bionic
      otp_release: 23.3.1

    - os: linux
      dist: focal
      otp_release: 24.3.1

    - os: linux
      dist: focal
      otp_release: 25.0

    - os: osx
      osx_image: xcode12.2
      language: generic

before_script:

- if [[ $TRAVIS_OS_NAME == osx ]]; then brew install erlang || true; fi

- curl https://s3.amazonaws.com/rebar3/rebar3 --output rebar3 && chmod +x rebar3

script:
    - ./rebar3 compile

after_success:
    - make ct
